# Generated by Django 3.0.8 on 2020-07-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200724_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='article_media',
        ),
    ]
